import { MainLayout } from '@/components/layout/main'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme/theme-provider"
import { Providers } from '@/redux/providers'
import { MainLayoutProvider } from '@/components/layout/main/context-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrollbar-thin scrollbar-thumb-scrollbar`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <MainLayoutProvider>
              <MainLayout>
                {children}
              </MainLayout>
            </MainLayoutProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
