import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "./globals.css";
import RootProvider from "@/components/providers/root-provider"

const nunito = Nunito({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: {
    template: '%s | NextJs Template',
    default: 'NextJs Template',
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <div className="light">
          <RootProvider>
            {children}
          </RootProvider>
        </div>
      </body>
    </html>
  );
}
